# Generated by Django 4.2 on 2023-04-22 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_cantidad_ventas_vendedor_meses_de_contrato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprador',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
