# Generated by Django 4.2 on 2023-05-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_remove_queja_anonima_remove_queja_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
