# Generated by Django 4.2 on 2023-04-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_infoextra_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='avatar_thumbnail',
            field=models.ImageField(default='avatares/default_thumbnail.png', upload_to='avatares/'),
        ),
    ]
