# Generated by Django 4.2 on 2023-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_infoextra_avatar_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='infoextra',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
