# Generated by Django 4.2 on 2023-05-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_infoextra_description_infoextra_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoextra',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='infoextra',
            old_name='website',
            new_name='enlace_pagina',
        ),
    ]
